export enum AnalyticsActionResult {
    Error = 'error',
    Success = 'success',
    NotFound = 'notFound',
    NoPhoto = 'noPhoto',
    NeedVerification = 'needVerification',
    Confirming = 'confirming',
    NotConfirmed = 'notConfirmed',
    Declined = 'declined',
    Inactive = 'inactive',
    UnavailableLegalReasons = 'unavailableLegalReasons',
    Booked = 'booked',
    NotBooked = 'notBooked',
    Allowed = 'allowed',
    NotAllowed = 'notAllowed',
    Prepared = 'prepared',
    NotPrepared = 'notPrepared',
    Delivered = 'delivered',
    NotDelivered = 'notDelivered',
    Available = 'available',
    NotAvailable = 'notAvailable',
    NewUser = 'newUser',
    Yes = 'yes',
    No = 'no',
}
