export enum AnalyticsActionType {
    AddBranch = 'addBranch',
    UpdateBranch = 'updateBranch',
    RemoveBranch = 'removeBranch',
    AddOffer = 'addOffer',
    RemoveOffer = 'removeOffer',
    Booking = 'booking',
    Permission = 'permission',
    Preparation = 'preparation',
    Delivery = 'delivery',
    Push = 'push',
    AddAppVersion = 'addAppVersion',
    RemoveAppVersion = 'removeAppVersion',
    AppStatus = 'appStatus',
    Attestation = 'attestation',
    Validation = 'validation',
    Check = 'check',
    GetGroups = 'getGroups',
    IsGroupAvailable = 'IsGroupAvailable',
    SignUp = 'signUp',
    SignOut = 'signOut',
}
